### ISSUE TITLE
Bad UX when using the "Approve wETH" functionality

### ISSUE THREAD

**Issue by jbrukh** [MolochVentures/moloch-monorepo#23] opened 2019-04-12 21:50 UTC
There is no sign the transaction is sent, validated, or rejected.

**Comment by rhlsthrm** [comment] 2019-04-12 22:23
Planning to implement a full transaction monitoring UX for all the onchain transactions, thanks for opening.

**Comment by rhlsthrm** [comment] 2019-04-12 22:24
Actually this is a duplicate of #13, I will close this in favor of that, which addresses all transactions, not just "approve wETH".

**Closed by rhlsthrm** 2019-04-12 22:24 UTC
